### ISSUE TITLE
Backs of cards are missing

### ISSUE THREAD

**Issue by tobiasprinz** [any2cards/gloomhaven#1]
Heya,

I am quite happy to have found this project. It is really awesome, I am going to print myself a 5th player attack modifier deck and some replacement cards for the less-randomness-variant.

But I noticed that the backs of the cards are missing. I wonder whether I could simply scan them myself and create a pull request to add them - that would depend on a) the scope of the project and b) the rights associated with it.

Can someone clue me in whether I should do this?

**Comment by any2cards** [comment]
The purpose of this repository is to power the GCV, which is used to display the fronts of the cards.  The backs, for the purpose of the GCV, have no value.  Having said that, most of the repository types do have their backs within the respective folders (most of them ending in "-back".  If you tell me specifically what you are looking for, I will make sure they are added, if they are missing.

**Comment by tobiasprinz** [comment]
Thanks, @any2cards , after posting this I found the backs for most cards, except for 

- attack modifiers
- items

@stimm4711 
Thanks for the advice. I know about them. I simply prefer to make my own ;-)

**Comment by any2cards** [comment]
Here is a DropBox link within which are samples of the attack-modifier and item backs.  Please note that each individual item back is unique because it is numbered.  I have included number 001.  If you use a tool like GIMP, you should be able to modify it to meet your needs.

[GH Card Backs](https://www.dropbox.com/sh/b7n4e5sguy2wnax/AACkUGWKzCZQj4XTAIjnQXJ5a?dl=0)
